### ISSUE TITLE
Logging in test/break_test.exs terminal-bomb the screen

### ISSUE THREAD

**Issue by jackalcooper** [RustySnek/Venomous#13]
Logging in `test/break_test.exs` is so excessive. Is it possible to capture the output with functions in [`ExUnit.CaptureLog`](https://hexdocs.pm/ex_unit/ExUnit.CaptureLog.html#content)?

**Comment by RustySnek** [comment]
Yeah this was terrible to work with, I've fixed most of it in #14 
Most of it meaning there is still one :exit error message that persists for some reason. But I guess that's better than spamming 30 pdf pages of unnecessary errors.
I've also piped the stderr of OS kill process to /dev/null so it doesn't spit out the "process does not exist" in case the python process already died.
Let me know what you think about this
